spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false


  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
    redis:
      host: ${REDIS_HOST}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER_NAME}
    password: ${DATASOURCE_PASSWORD}

server:
  servlet:
    encoding:
      charset: UTF-8

    multipart:
      max-request-size: 20MB
      max-file-size: 20MB

#AWS-S3 Bucket
cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    stack:
      auto-: 'false'
    region:
      static: ap-northeast-2

application:
  s3:
    poll-item:
      dir: "gollaba-image-bucket-dev"


springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    enabled: false
    path: /api-docs/gollaba
  swagger-ui:
    url: /api-docs/gollaba/main.json
    path: /v2/gollaba/