spring:
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
    redis:
      host: 127.0.0.1
      port: 639

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: # 멘토님 저도 이거 하고시퍼요
    username: # 근데 실패해서 코드 실행도 안되는 거 같아요
    password: # ㅠㅠㅠㅠ 나도 로컬로 돌리고 레디스 따로 설정하고시퍼요 ㅠㅠㅠㅠ

server:
  servlet:
    encoding:
      charset: UTF-8