name: backend-build-prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to EC2 and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PROD_SSH_KEY }}
          port: ${{ secrets.EC2_PROD_PORT }}
          script: |
            cd /home/ec2-user/gollaba-deploy-prod
            ./deploy-prod.sh
